[package]
name = "leptos_todo"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.6.12", features = ["csr"] }
leptos-use = { version = "0.10.10", features = ["serde"] }
serde = { version = "1.0.203", features = ["derive"] }
